language: go
go_import_path: github.com/iostrovok/cacheproxy
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
sudo: required
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.14.x, 1.15.x, 1.16.x]
os: [linux, osx]
install:
  - make mod
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - rm -f  ./cassettes/*
  - make mod
  - make test-travis
  - rm -f ./cassettes/*
jobs:
  fast_finish: true

