language: go
go_import_path: github.com/iostrovok/cacheproxy
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.13.x, 1.14.x]
os: [linux, osx]
install:
  - make mod
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - rm -f  ./cassettes/*
  - make test-travis
  - rm -f ./cassettes/*

